- ProxyStubGenerator/StubGenerator.py
No point in deprecated use warnings when compiling proxy stubs. The stub code cannot do anything about the fact there is a deprecated method on an interface.
> [StubGen] Silence deprecated use warnings

- JsonGenerator/source/class_emitter.py
- JsonGenerator/source/header_loader.py
This solves mutliple definition error on linking enum registrateion code if multiple interfaces use the same enum by alias (i.e. typedef/using).
> [JsonGen] Don't emit enum registration tables for aliases

- JsonGenerator/source/class_emitter.py
> [Warnings] Removing the semicolon after enum macros to suppress warnings

- JsonGenerator/source/documentation_generator.py
- JsonGenerator/source/header_loader.py
- JsonGenerator/source/json_loader.py
- ProxyStubGenerator/CppParser.py
- ProxyStubGenerator/Log.py
- ProxyStubGenerator/StubGenerator.py
support float and double but block long double
> [StubGen/JsonGen] Add floating-point types support

- JsonGenerator/source/documentation_generator.py
- JsonGenerator/source/header_loader.py
- JsonGenerator/source/rpc_emitter.py
- ProxyStubGenerator/CppParser.py
- ProxyStubGenerator/StubGenerator.py
If an output iterator is marked as `@extract` and there is only one element in the list, then the resulting JSON element will omit the array (i.e. with no square brackets around).
Needs https://github.com/rdkcentral/Thunder/pull/1462.
> [JsonGen] Add @extract keyword

- JsonGenerator/JsonGenerator.py
- JsonGenerator/source/code_generator.py
- JsonGenerator/source/config.py
- ProxyStubGenerator/StubGenerator.py
- cmake/FindJsonGenerator.cmake.in
--cpp-output to specify dedicated output directory for generated .cpp files
Introduced addtiontal json_*.h headr with collection of other generated files
changes EXTERNAL to EXTERNAL_EXPORT in metadata
> [JsonGen] Add --cpp-output option and header collection

- JsonGenerator/source/config.py
- JsonGenerator/source/header_loader.py
- cmake/FindJsonGenerator.cmake.in
Legacy behavior reachable with --auto-prefix switch.
> [JsonGen] Don't prefix RPC endpoint names with namespace

- ConfigGenerator/params.config
- JsonGenerator/source/documentation_generator.py
- cmake/FindConfigGenerator.cmake.in
Make sure the AutoStart flag is no longer used or published as it is superseded by the already existing startmode enum together eith the resumed flag (boolean).
> [STARTMODE] Preperations for R5, starmode supersedes the autostart flag.

- ProxyStubGenerator/Log.py
- ProxyStubGenerator/StubGenerator.py
Adds `@length:return` to be used when the length of a returned buffer is carried on the return value.
This allows for optimizations:
- not sending the entire possible buffer on the inbound message (i.e. from maxlength), but just what was really filled in,
- omitting sending of the result on the inbound message (as the length is already sent within the buffer).
This is used in ICryptography.
Additionally fixed a bug that mixed length with maxlength fixing previously broken `IPerformance::Exchange()`. Additional optimizations are applicable now as above.
Also fixes emitting of some tautology code, making compiler happy.
> [StubGen] Intruduce length:return

- .github/workflows/Build ThunderTools on Linux.yml
Same as with the Thunder PR: https://github.com/rdkcentral/Thunder/pull/1496
This is an initial pull request - the new workflows have to be called from my branches for now (there is a dependency between the workflows), since we need to first merge new templates in each repo. Then, I'll make one more set of pull requests to redirect this new feature to master branches of our repos.
Required checks got updated to the new ones by Stephen.
> [Actions] Thunder will be the only build required to merge, but Actions will also build other components

- .github/workflows/Build ThunderTools on Linux.yml
The last set of pull requests, now the new Actions will use workflows from our repos instead of my forks, which sadly couldn't have been done in one go.
> [Actions] Using the already merged workflows instead of my forks

- .github/workflows/Build ThunderTools on Linux.yml
- ConfigGenerator/json_helper.py
- ConfigGenerator/params.config
- DocumentGenerator/DocumentGenerator.py
- JsonGenerator/JsonGenerator.py
- JsonGenerator/source/class_emitter.py
- JsonGenerator/source/code_generator.py
- JsonGenerator/source/config.py
- JsonGenerator/source/documentation_generator.py
- JsonGenerator/source/emitter.py
- JsonGenerator/source/header_loader.py
- JsonGenerator/source/json_loader.py
- JsonGenerator/source/rpc_emitter.py
- JsonGenerator/source/trackers.py
- LuaGenerator/GenerateLua.sh
- ProxyStubGenerator/CppParser.py
- ProxyStubGenerator/Log.py
- ProxyStubGenerator/StubGenerator.py
- ProxyStubGenerator/default.h
- cmake/FindConfigGenerator.cmake.in
- cmake/FindJsonGenerator.cmake.in
- cmake/FindProxyStubGenerator.cmake.in
This change is made so that the below code in UnknownStubType doesn't accidentally walk over any data (that might be initialized with non-zero value)
```
template <typename INTERFACE, MethodHandler METHODS[]>
class UnknownStubType : public UnknownStub {
...
UnknownStubType()
{
_myHandlerCount = 0;
while (METHODS[_myHandlerCount] != nullptr) {
_myHandlerCount++;
}
}
...
} 
```
This issue was identified by AddressSanitizer as below
```
==30==ERROR: AddressSanitizer: global-buffer-overflow on address 0xe3815db8 at pc 0xe37e9105 bp 0xffaf6008 sp 0xffaf600c
READ of size 4 at 0xe3815db8 thread T0
#0 0xe37e9102  (/usr/libexec/asan_lib/usr/lib/libWPEFrameworkCOM.so.4+0x59102)
#1 0xe37a740a  (/usr/libexec/asan_lib/usr/lib/libWPEFrameworkCOM.so.4+0x1740a)
0xe3815db8 is located 0 bytes to the right …
```
> Delimit StubMethods array with nullptr explicitly

- JsonGenerator/source/class_emitter.py
- JsonGenerator/source/documentation_generator.py
- JsonGenerator/source/header_loader.py
- JsonGenerator/source/json_loader.py
- JsonGenerator/source/rpc_emitter.py
- ProxyStubGenerator/CppParser.py
- ProxyStubGenerator/StubGenerator.py
- ProxyStubGenerator/default.h
- OptionalType<T> now works with indexes,
- OptionalType<T> now works where T is Iterator*,
- OptionalType<T> now works where T is bitmask,
- OptionalType<T> now works with stub security,
- `@restrict` now works with indexes,
- `@default` is now checked against `@restrict` range (compile time),
- indexes to setter/getter can now differ by OptionalType, `@optional`, `@restrict` and `@default`,
- bool can now also be used as index type.
`@optional` is still supported and also handles `@default` but is made redundant by OptionalType
> OptionalType for index and iterators

- JsonGenerator/source/class_emitter.py
- JsonGenerator/source/header_loader.py
- JsonGenerator/source/rpc_emitter.py
- ProxyStubGenerator/CppParser.py
- ProxyStubGenerator/StubGenerator.py
```
struct Fixated {
struct BluetoothInfo {
uint8_t Addr[6]; // a bt address
uint32_t UUIDs[8];
string Descriptions[8];
};
uint8_t IpAddr[4]; // an ip address
BluetoothInfo BtAddr[5]; 
uint8_t Edid[128] /* @encode:base64 */;
};
virtual Core::hresult Amazing(Fixated param[4] /* @inout */) = 0;
```
Supports all types including PODs, supports nesting.
> [JsonGen/StubGen] Support fixed arrays

- DocumentGenerator/requirements.txt
**To fix the below issue:**
`AttributeError: cython_sources`
_PyYAML version changed from 6.0 to 6.0.2_
**To fix below issue:**
`AttributeError: 'EntryPoints' object has no attribute 'get'`
_importlib-metadata version changed from 4.8.1 to 8.5.0_
_Markdown version changed from 3.3.4 to 3.7_
**To have Markdown 3.7 to be installed:**
_zipp version changed from 3.6.0 to 3.20_
> Updating python dependencies to make DocumentGenerator script work again

- JsonGenerator/source/json_loader.py
This is needed for IAudioStream.
> [JsonGen] Don't verify bitmask value for enum -end- marker

- PluginSkeletonGenerator/file_data.py
- PluginSkeletonGenerator/utils.py
@nxtum in theory this change should only get rid of the warning and not change the functionality, because so far Python was ignoring the backslash anyway, due to the fact that you cannot escape a star in a string (unless it is marked as a raw string with `r` in front of it, in which case backslash would be treated literally, and not as an escape character).
The question is - did you have in mind to have a literal backslash in this string? 😄
> [PluginSkeletonGenerator] Fix a warning about trying to escape star in Python

- JsonGenerator/source/class_emitter.py
- JsonGenerator/source/emitter.py
- JsonGenerator/source/header_loader.py
- JsonGenerator/source/json_loader.py
- JsonGenerator/source/rpc_emitter.py
- support @encode:base64 for std::vector
- support @encode:mac and @encode:hex for uint8_t* buffer, array[] and std::vector
- array[] and std::vector can be now property index (if @encode is used)
- array[] and std::vector can now be id in notification (if @encode is used)
- Core::OptionalType can now be id in notification
> [JsonGen] Buffer encoding enhancements

- JsonGenerator/source/class_emitter.py
- JsonGenerator/source/rpc_emitter.py
If an element is not optional it is always emitted, including arrays as [] and objects as {}.
Unset optional elements are omitted, unless the element is the result of JSON-RPC "result" field, then it is emitted as null.
> [JsonGen] Serialize empty non-optional arrays and objects

- JsonGenerator/source/class_emitter.py
- JsonGenerator/source/header_loader.py
- ProxyStubGenerator/CppParser.py
- ProxyStubGenerator/StubGenerator.py
with syntax @restrict:5..
also adds some sanity checks on restrict input and fixes bug where restricted integer and float parameters were not verified in json-rpc
> Allow setting only lower bound of @restrict range
