ProxyStubGenerator/CppParser.py
ProxyStubGenerator/Log.py
ProxyStubGenerator/StubGenerator.py
cmake/FindProxyStubGenerator.cmake.in

- nested PODs
- secure mode (frame integrity checking, range checking, partial 'restrict' keyword support),
- does not sent duplicate buffer size twice,
- ccstring support,
- 25% faster

[StubGen] Optimizations, restrict, nested PODs, ccstring

---

ProxyStubGenerator/StubGenerator.py

Simple is the best!... Flies on gcc and msvc.

[StubGen] Fix stubbed methods

---

JsonGenerator/GenerateDocs.sh
ProxyStubGenerator/StubGenerator.py

Requires https://github.com/rdkcentral/Thunder/pull/1290

[StubGen] Fix restrict with strings

---

ProxyStubGenerator/CppParser.py
ProxyStubGenerator/StubGenerator.py

[DependsOn=Thunder:development/int24]

[StubGen] Support int24

---

LuaGenerator/GenerateLua.bat
LuaGenerator/GenerateLua.sh
ProxyStubGenerator/StubGenerator.py

Corrects a small bug during ICompostion scanning by luagenerator

[StubGen] Also consider non-pure-virtual methods for interface dump

---

JsonGenerator/JsonGenerator.py
JsonGenerator/source/class_emitter.py
JsonGenerator/source/code_generator.py
JsonGenerator/source/documentation_generator.py
JsonGenerator/source/emitter.py
JsonGenerator/source/header_loader.py
JsonGenerator/source/json_loader.py
JsonGenerator/source/rpc_emitter.py
JsonGenerator/source/trackers.py
ProxyStubGenerator/CppParser.py

Also resovle problems with duplicate enum registration if multiple interfaces share same enums.

[JsonGen] Add support for prefix tag

---

.github/workflows/Build ThunderTools on Windows.yml

[Actions] Building bridge and all possible plugins on Windows to properly test the generators

---

JsonGenerator/source/header_loader.py
ProxyStubGenerator/CppParser.py
ProxyStubGenerator/StubGenerator.py

Supports any inheritance depth and multiple inheritance, including virtual inheritance.
Some limitation:
- struct inheritance must be public, 
- all members must be public,
- in case when two or more super-classes share a common base class (e.g. do a diamond) then virtual inheritance is required.
All above is checked for.

[StubGen/JsonGen/LuaGen] Support POD inheritance

---

DocumentGenerator/DocumentGenerator.py
JsonGenerator/JsonGenerator.py
JsonGenerator/source/documentation_generator.py

Decouples DocumentGenerator deployment tool from JsonGenerator internals. Use its command line API instead.

[DocGen] Don't use JsonGen internals

---

JsonGenerator/source/config.py
cmake/FindJsonGenerator.cmake.in

add `EMIT_INTERFACE_PATH qa_interfaces` in cmake JsonGenerator invocation

[JsonGen] Configurable emitted interface path

---

cmake/FindJsonGenerator.cmake.in

Curious if my first CMake contributions is correct (it is more Monkey see, Monkey do I must admit :) )

[JsonGen] add options to JsonGen cmake.in

---

ProxyStubGenerator/StubGenerator.py

[StubGen] Don't complain on omitted interfaces

---

JsonGenerator/JsonGenerator.py
JsonGenerator/source/class_emitter.py
JsonGenerator/source/code_generator.py
JsonGenerator/source/documentation_generator.py
JsonGenerator/source/header_loader.py
JsonGenerator/source/json_loader.py
JsonGenerator/source/rpc_emitter.py
ProxyStubGenerator/Interface.py
ProxyStubGenerator/StubGenerator.py

also fixes generating event code without native Register methods present
also fixes generating code for event-only interfaces
also add support for sending one event by multiple methods

[JsonGen] Support iterators in events

---

ConfigGenerator/params.config
JsonGenerator/source/documentation_generator.py
JsonGenerator/source/rpc_emitter.py
cmake/FindConfigGenerator.cmake.in

This resolves building issues with R4_4 baseline and updated tools.

Sync tools with R4_4 code

---

DocumentGenerator/DocumentGenerator.py

A minor change for commit message where we push ServiceDocumentation gh-pages via python script.

Minor change for commit message

---

DocumentGenerator/DocumentGenerator.py

Otherwise, emojis are not shown correctly!

Updating deprecated materialx emojis to material extensions

---

JsonGenerator/source/documentation_generator.py
JsonGenerator/source/emitter.py
JsonGenerator/source/header_loader.py
JsonGenerator/source/json_loader.py
JsonGenerator/source/rpc_emitter.py
ProxyStubGenerator/StubGenerator.py

[DependsOn=Thunder:development/fix-const-on-interface]

[JsonGen] Automatic object lookup

---

JsonGenerator/source/class_emitter.py
JsonGenerator/source/documentation_generator.py
JsonGenerator/source/emitter.py
JsonGenerator/source/header_loader.py
JsonGenerator/source/json_loader.py
JsonGenerator/source/rpc_emitter.py
JsonGenerator/source/trackers.py
ProxyStubGenerator/CppParser.py
ProxyStubGenerator/StubGenerator.py
ProxyStubGenerator/default.h

+support fixed arrays in json events

Add std::vector support

---

ProxyStubGenerator/StubGenerator.py

[DependsOn=Thunder:development/remove-clashing-methods]

[StubGen] Avoid direct calls to UnknownProxyType

---

JsonGenerator/source/rpc_emitter.py

[DependsOn=Thunder:development/facilitate-statuslistener-in-lookup]

[JsonGen] Support statuslistener for lookup objects

---

JsonGenerator/source/class_emitter.py
JsonGenerator/source/documentation_generator.py
JsonGenerator/source/header_loader.py
JsonGenerator/source/json_loader.py
JsonGenerator/source/rpc_emitter.py
JsonGenerator/source/trackers.py

1. Arrays, vectors, buffers, optional encoded can be used in events and async methods.
2. Fixes documentation with encoded types.

[JsonGen] Support encoded arrays/vectors/buffers in events

---

JsonGenerator/source/header_loader.py
JsonGenerator/source/rpc_emitter.py

[DependsOn=Thunder:development/jsonrpc-use-string-as-instanceid]

[JsonGen] Use string instance id

---

.github/workflows/Build ThunderTools on Linux.yml
.github/workflows/Build ThunderTools on MacOS.yml
.github/workflows/Build ThunderTools on Windows.yml

This is a fix for [this](https://github.com/rdkcentral/Thunder/security/code-scanning/15) code scanning alert

 [Actions] Add permissions to all workflows
